#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xdg-dbus-proxy
Version  : 0.1.4
Release  : 4
URL      : https://github.com/flatpak/xdg-dbus-proxy/releases/download/0.1.4/xdg-dbus-proxy-0.1.4.tar.xz
Source0  : https://github.com/flatpak/xdg-dbus-proxy/releases/download/0.1.4/xdg-dbus-proxy-0.1.4.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: xdg-dbus-proxy-bin = %{version}-%{release}
Requires: xdg-dbus-proxy-license = %{version}-%{release}
Requires: xdg-dbus-proxy-man = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)

%description
xdg-dbus-proxy
==============
xdg-dbus-proxy is a filtering proxy for D-Bus connections. It was originally
part of the flatpak project, but it has been broken out as a standalone module
to facilitate using it in other contexts.

%package bin
Summary: bin components for the xdg-dbus-proxy package.
Group: Binaries
Requires: xdg-dbus-proxy-license = %{version}-%{release}

%description bin
bin components for the xdg-dbus-proxy package.


%package license
Summary: license components for the xdg-dbus-proxy package.
Group: Default

%description license
license components for the xdg-dbus-proxy package.


%package man
Summary: man components for the xdg-dbus-proxy package.
Group: Default

%description man
man components for the xdg-dbus-proxy package.


%prep
%setup -q -n xdg-dbus-proxy-0.1.4
cd %{_builddir}/xdg-dbus-proxy-0.1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1652295051
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1652295051
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xdg-dbus-proxy
cp %{_builddir}/xdg-dbus-proxy-0.1.4/COPYING %{buildroot}/usr/share/package-licenses/xdg-dbus-proxy/01a6b4bf79aca9b556822601186afab86e8c4fbf
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xdg-dbus-proxy

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xdg-dbus-proxy/01a6b4bf79aca9b556822601186afab86e8c4fbf

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xdg-dbus-proxy.1
